"""initial schema: historical_price, forecast, model_metric

Revision ID: 2af9629b199c
Revises: 
Create Date: 2026-07-24 18:32:37.931456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af9629b199c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vegetable', sa.String(length=32), nullable=False),
    sa.Column('model_family', sa.String(length=64), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_forecast_date'), 'forecast', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecast_model_family'), 'forecast', ['model_family'], unique=False)
    op.create_index(op.f('ix_forecast_vegetable'), 'forecast', ['vegetable'], unique=False)
    op.create_index('ix_forecast_vegetable_model_date', 'forecast', ['vegetable', 'model_family', 'forecast_date'], unique=True)
    op.create_table('historical_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vegetable', sa.String(length=32), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('wholesale_price', sa.Float(), nullable=True),
    sa.Column('retail_price', sa.Float(), nullable=False),
    sa.Column('average_temperature', sa.Float(), nullable=True),
    sa.Column('average_rainfall', sa.Float(), nullable=True),
    sa.Column('diesel_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_price_vegetable'), 'historical_price', ['vegetable'], unique=False)
    op.create_index('ix_historical_price_vegetable_week', 'historical_price', ['vegetable', 'week_start'], unique=True)
    op.create_index(op.f('ix_historical_price_week_start'), 'historical_price', ['week_start'], unique=False)
    op.create_table('model_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vegetable', sa.String(length=32), nullable=False),
    sa.Column('model_family', sa.String(length=64), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mape', sa.Float(), nullable=False),
    sa.Column('r2', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metric_model_family'), 'model_metric', ['model_family'], unique=False)
    op.create_index(op.f('ix_model_metric_vegetable'), 'model_metric', ['vegetable'], unique=False)
    op.create_index('ix_model_metric_vegetable_model', 'model_metric', ['vegetable', 'model_family'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_metric_vegetable_model', table_name='model_metric')
    op.drop_index(op.f('ix_model_metric_vegetable'), table_name='model_metric')
    op.drop_index(op.f('ix_model_metric_model_family'), table_name='model_metric')
    op.drop_table('model_metric')
    op.drop_index(op.f('ix_historical_price_week_start'), table_name='historical_price')
    op.drop_index('ix_historical_price_vegetable_week', table_name='historical_price')
    op.drop_index(op.f('ix_historical_price_vegetable'), table_name='historical_price')
    op.drop_table('historical_price')
    op.drop_index('ix_forecast_vegetable_model_date', table_name='forecast')
    op.drop_index(op.f('ix_forecast_vegetable'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_model_family'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_forecast_date'), table_name='forecast')
    op.drop_table('forecast')
    # ### end Alembic commands ###
